config/routes.rb
Rails.application.routes.draw do
 devise_for :users
 root "homes#top"
 get "home/about" => "homes#about", as: :about
 resources :users, only: [:index, :show, :edit, :update]
 resources :books do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
 end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  attachment :profile_image
  
  validates :name, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "sign out successfully."
    root_path
  end
  def after_sign_in_path_for(resource)
    flash[:notice] = "sign in successfully."
    user_path(current_user.id)
  end
  
  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |user| user.permit(:name, :email, :password) }
    end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      redirect_to book_path(@book)
    else
      redirect_back fallback_location: root_path
    end
  end
    
    
  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

 before_action :authenticate_user!
 before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if  @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render "index"
    end
  end

  def show #find_byなら死ぬ
    @showbook = Book.find(params[:id])
    @book = Book.new
    @user = @showbook.user
    @book_comment = BookComment.new
  end

  def edit
    book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params) 
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
#https://qiita.com/ryuuuuuuuuuu/items/73cf2708b31c4cb901ec
#何故かうまくいくからuserにもブチ込むといい感じ
 def correct_user
   @book = Book.find(params[:id])
   if current_user.id != @book.user.id      
    redirect_to books_path    
   end
 end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back fallback_location: root_path
# https://railsdoc.com/page/redirect_back
    end
    
    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back fallback_location: root_path

    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path
    else
      render "edit"
    end
  end
  protected
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  #https://qiita.com/ryuuuuuuuuuu/items/73cf2708b31c4cb901ec
  #何故かうまくいくからuserにもブチ込むといい感じ
  def correct_user
   @user = User.find(params[:id])
   if current_user != @user
    redirect_to user_path(current_user.id)
   end
  end
 
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/bookcomments_helper.rb
module BookcommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice">
</p>

<!--c,r colmd8で安定しやすかも-->
<div class="container">
<div class="row">
<div class="col-md-8 col-sm-12 px-sm-0 mx-auto">
  
<!--何故かこれで動く、不明https://stackoverflow.com/questions/59523676/ruby-on-rails-encountered-a-syntax-error-while-rendering-template-->
  <h1>Editing Book</h1>
  <div class="errors-text">
      <% if @book.errors.any? %>
    <h3>
      <%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:
    </h3>
    　<% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    　<% end %>
    　<% end %>
  </div>
  
  
  <%= form_with model:@book, local: true do |f| %>
  
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>

    <%= f.submit "Update Book", class:"btn btn-success" %>
    <% end %>

  <p>
    <%= link_to "Show", book_path(@book) %> |
    <%= link_to "Back", books_path %>
  </p>
      
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice">
</p>

<!--.container .row .col-md-3' container .row .col-md-3-->
<div class="container px-5 ">
<div class="errors-text col-md-3">
  <% if @book.errors.any? %>
<h2>
  <%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:
</h2>
   <% @book.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
  <% end %>
 </div>
  
<!--.container .row .col-md-3' container .row .col-md-3-->
<div class="row">
<div class="col-md-3">
<%= render "layouts/form", user: @user %>
      
<%= render "layouts/create", book: @book %>
    </div>
    
    
 <!--.container .row .col-md-8.offset-md-1-->
<div class="col-md-8 offset-md-1 ">
  <h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    
  <tr>
   <th>Title</th>
   <th>Opinion</th>
   <th colspan="3"></th>
  </tr>
  
  </thead>
  
<tbody>
  <% @books.each do |book| %>
  <tr><td>
    <%= link_to user_path(book.user) do %>
    <%= attachment_image_tag  book.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
    <% end %>
    
  </td><td>
    <%= link_to book_path(book) do %>
    <%= book.title %>
    <% end %>

  </td><td>
    <%= book.body %>
    
  </td>
<% if book.favorited_by?(current_user) %>
  <td>
    <%= link_to book_favorites_path(book.id), method: :delete do %>
    <i class="fas fa-heart"></i><%= book.favorites.count %>
    <% end %>
  </td>
<% else %>
  <td>
    <%= link_to book_favorites_path(book), method: :post do %>
    <i class="far fa-heart"></i><%= book.favorites.count %>
    <% end %>
   </td>
<% end %>
    <td>コメント数:<%= book.book_comment_ids.count %></td>
<% end %>
  </tr>  
    
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!--saccses messsage?入れとくとEr消える-->
<p id="notice"><%if flash[:notice] %>
  <%= flash[:notice]  %>
<% end %></p>


<!--c、r、cmd3-->
<div class="container">
  <div class="row">
<div class="col-md-3">
    <%= render "layouts/form", user: @user %>
    <%= render "layouts/create", book: @book %>
</div>
    <!--.container .row .col-md-8.offset-md-1-->
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    
    <tr>
    <td>
    <%= link_to user_path(@showbook.user) do %>
    <%= attachment_image_tag  @showbook.user, :profile_image, size: "50x50", fallback: "no_image.jpg" %><br>
    <%= @showbook.user.name %></br>
    <% end %>
    </td>
    
    <td>
     <%= link_to book_path(@showbook) do %>
     <%= @showbook.title %>
     <% end %>
    </td>
    
    <td>
     <%= @showbook.body %>
    </td>
      <div class="navbar-collapse collapse" id="navbarNavDropdown">
    <% if @showbook.favorited_by?(current_user) %>
        <td>
            <%= link_to book_favorites_path(@showbook.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= @showbook.favorites.count %>
            <% end %>
        </td>
    <% else %>
        <td>
            <%= link_to book_favorites_path(@showbook), method: :post do %>
            <i class="far fa-heart"></i><%= @showbook.favorites.count %> 
            <% end %>
        </td>
    <% end %>
    </div>
    
    <td>
     <%if @showbook.user.id == current_user.id  %>
     <%= link_to "Edit", edit_book_path(@showbook), class:"btn btn-sm btn-success" %>
     <% end %>
    </td>
    
    <td><!--https://qiita.com/iverson3kobe0824/items/3baa1d57843fbde6cd19-->
     <%if @showbook.user.id == current_user.id  %>
     <%= link_to "Destroy", book_path(@showbook), method: :delete, data: { confirm: "削除しますか？" }, class:"btn btn-sm btn-danger" %>
     <% end %>
    </td>
    </tr>
    
      </table>
    <table>
    <% @showbook.book_comments.each do |book_comment| %>
        <tbody>

        <td><%= attachment_image_tag book_comment.user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg"%></td>
        <td><%= book_comment.comment %></td>
    <td>
        <% if book_comment.user == current_user %>
        <td><%= link_to "Destroy",  book_book_comment_path(book_comment.book, book_comment), method: :delete, class:"btn-sm btn-danger destroy_book"%></td>
        <% end %>
    </td>
        </tbody>
    <% end %>
    </table>
    <br>
    
    <%= form_with(model:[@showbook, @book_comment], local: true) do |f| %>
    <%= f.text_area :comment, rows:'5', class: "form-control"%>
    <%= f.submit "送信", class: "pull-right" %>
    <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container row">
  
  <h1 class="px-3 mx-auto">Welcome to 
  <i class="fas fa-book"></i>
  <strong>Bookers</strong>!</h1>
  
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice]  %></p>
<% end %>

<div class="container">
  <div class="row mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
     
  <div class="social">
    
    <h1>welcome to 
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>!!</h1>
    
  </div>

  <div class="social">
    <p>In
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>,</p>
  </div>

  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
  
  
  <div class="btn-wrapper col-10 mx-auto">
  <div class="row" >
    <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
  </div>

  <div class="row">
    <%= link_to "Sign Up", new_user_registration_path,  class:"btn btn-success btn-sm btn-block" %>
  </div>
  
      </div>
    </div>
  </div>
</div>

app/views/layouts/_create.html.erb
<h2 class="mt-3">New book</h2>

<%= form_with model:book, local:true do |f| %>

  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class:"form-control" %>
  </div>

  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>

  <%= f.submit "Create Book", class:"btn btn-success" %>

<% end %>

app/views/layouts/_form.html.erb
<h2>User info</h2>
 <%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tbody>
    
  <tr>
    <td>name</td>
    <td><%= user.name %></td>
  </tr>
  
  <tr>
    <td>introduction</td>
    <td><%= user.introduction %></td>
  </tr>
  </tbody>
</table>


<div class="row">
    <%= link_to "", edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar-dark bg-dark">
   <div class="navbar navbar-expand-lg">
   <div class="container">
        <%= link_to "Bookers", root_path, class:"navbar-brand" %>
        <!--https://getbootstrap.jp/docs/4.2/components/navbar/?#color-schemes-->
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
  <div class="navbar-collapse collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
  <!--pathじゃないとエラー出る iでロゴ判定でない-->    
  <% if user_signed_in? %>
      <li><%= link_to "Home", user_path(current_user.id), class:"nav-link text-white fas fa-home" %></li>
      <li><%= link_to "Users", users_path, class:"nav-link text-white fas fa-users" %></li>
      <li><%= link_to "Books", books_path, class:"nav-link text-white fas fa-book-open" %></li>
      <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"nav-link text-white fas fa-sign-out-alt" %></li>
  <% else %>
      <li><%= link_to "Home", root_path, class:"nav-link text-white fas fa-home" %></li>
      <li><%= link_to "About", about_path, class:"nav-link text-white fas fa-link" %></li>
      <li><%= link_to "sign up", new_user_registration_path, class:"nav-link text-white fas fa-user-plus" %></li>
      <li><%= link_to "login", new_user_session_path, class:"nav-link text-white fas fa-sign-in-alt" %></li>
  <% end %>
          </div>
  </div>
  </div>

  </header>

    <%= yield %>

    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p col-lg-6>CopyRight Infratop.inc</p>
          
        </div>
      </div>
    </div>

  </body>
</html>

app/views/users/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <!-- colmd8確定で微調整していく-->
    <div class="col-md-8 col-sm-12 px-sm-0 mx-auto">
      <h2>User info</h2>
  <!--これで動いた流用したとこ-->
  <div class="errors-text">
  <% if @user.errors.any? %>
    <h3>
      <%= pluralize(@user.errors.count, "error") %> prohibited this product from being saved:
    </h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
    <li>
      <%= message %>
    </li>
      <% end %>
    </ul>
  <% end %>
  </div>
  
  <%= form_with model: @user, local:true do |f|%>
  <!-- テキスト＋ネームでも通る？-->
    <div class="form-group">
      <label>Name</label>
       <%= f.text_field :name, class:"form-control" %>
    </div>
    
    <div class="form-group">
      <label>Image</label></br>
      <%= f.attachment_field :profile_image %>
    </div>
    
    <div class="form-group">
      <label>Introduction</label>
      <%= f.text_area :introduction, class:"form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.submit "Update User", class:"btn btn-secondary" %>
    </div>
    
  <% end %>
  
  
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice">
</p>


<div class="container  px-5 px-sm-0">
  <div class="row">
    
    
  <div class="col-md-3">
    <%= render "layouts/form", user: @user %>
    <%= render "layouts/create", book: @book %>
  </div>
  
  
  <!--ofmd1 colmd8 -->
  <div class="offset-md-1 col-md-8">
  <h2>Users</h2>
  <table class="table">
  <thead>
  <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
    
    
  <% @users.each do |user| %>
    <tr><td>
    <%= attachment_image_tag  user, :profile_image, size: "50x50", fallback: "no_image.jpg" %>
    
    </td><td>
    <%= user.name %>
    </td><td>
    <%= link_to "Show", user_path(user) %>
    </td></tr>
  <% end %>
    
    
        </body>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="notice">
<p id="notice">
  <%if flash[:notice] %>
    <%= flash[:notice]  %>
  <% end %>
</p>
</div>

<div class="container px-5 px-md-0">
  <div class="row">
    
    
    <div class="col-md-3">
      <%= render "layouts/form", user: @user %>
      <%= render "layouts/create", book: @book %>
    </div>
    
    
    <div class="offset-md-1 col-md-8">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
  
  <thead>
    <tr>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
    </tr>
  </thead>
    
  <tbody>
  <% @books.each do |book| %>
    <tr><td>
      <!--https://qiita.com/iverson3kobe0824/items/3baa1d57843fbde6cd19-->
      <%= link_to user_path(book.user) do %>
      <%= attachment_image_tag  @user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
      <% end %>

    </td><td>
      <%= link_to book_path(book) do %>
      <%= book.title %>
    <% end %>
    
    </td><td>
      <%= book.body %>
    
    </td></tr>
    <% end %>
  </tbody>
  
      </table>
    </div>
  </div>
</div>